apiVersion: v1
kind: Service
metadata:
  name: gatekey-openvpn-hub
  labels:
    app.kubernetes.io/name: gatekey
    app.kubernetes.io/component: openvpn-hub
spec:
  type: LoadBalancer
  ports:
    - port: 1194
      targetPort: openvpn
      protocol: UDP
      name: openvpn
  selector:
    app.kubernetes.io/name: gatekey
    app.kubernetes.io/component: openvpn-hub
