apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekey-openvpn-gateway
  labels:
    app.kubernetes.io/name: gatekey
    app.kubernetes.io/component: openvpn-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gatekey
      app.kubernetes.io/component: openvpn-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gatekey
        app.kubernetes.io/component: openvpn-gateway
    spec:
      containers:
        - name: openvpn-gateway
          image: dyetech/gatekey-gateway:1.2.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: openvpn
              containerPort: 1194
              protocol: UDP
          env:
            - name: GATEKEY_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: gatekey-vpn-config
                  key: server-url
            - name: GATEKEY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gatekey-vpn-tokens
                  key: openvpn-gateway-token
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
