apiVersion: v1
kind: Service
metadata:
  name: gatekey-wireguard-gateway
  labels:
    app.kubernetes.io/name: gatekey
    app.kubernetes.io/component: wireguard-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 51820
      targetPort: wireguard
      protocol: UDP
      name: wireguard
  selector:
    app.kubernetes.io/name: gatekey
    app.kubernetes.io/component: wireguard-gateway
