apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekey-wireguard-hub
  labels:
    app.kubernetes.io/name: gatekey
    app.kubernetes.io/component: wireguard-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gatekey
      app.kubernetes.io/component: wireguard-hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gatekey
        app.kubernetes.io/component: wireguard-hub
    spec:
      containers:
        - name: wireguard-hub
          image: dyetech/gatekey-wireguard-hub:1.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: wireguard
              containerPort: 51820
              protocol: UDP
          env:
            - name: GATEKEY_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: gatekey-vpn-config
                  key: server-url
            - name: GATEKEY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gatekey-vpn-tokens
                  key: wireguard-hub-token
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
